import { regalo } from "./regalo";

export const REGALI: regalo[] = [
  {id: 1,
  titolo: 'fasciatoio',
  immagini: [

  ],
  descrizione: 'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan',
  autore: 'maria',
  },
  {id: 2,
    titolo: 'biberon',
    immagini: [],
    descrizione: 'usato',
    autore: 'marco',
  },
  {id: 3,
    titolo: 'vestiti uomo',
    immagini: [],
    descrizione: 'taglia l',
    autore: 'maria',
  },
  {id: 4,
    titolo: 'macchina da cucire',
    immagini: [],
    descrizione: 'da sistemare',
    autore: 'chiara',
  },
  {id: 5,
    titolo: 'cappotto donna',
    immagini: [],
    descrizione: 'taglia medium',
    autore: 'chiara',
  },
];
